### ISSUE TITLE
How to use as a github action?

### ISSUE THREAD

**Issue by runspired** [percy/percy-ember#330]
With the deprecation of all the nice action flows, how does one use this in an action now?

**Comment by Robdel12** [comment]
Hey @runspired! The action only was needed to set env vars for Percy. Now you can run your test command in your CI config however that usually happens. For example, if this was before:

```yml
name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: yarn
      - name: Percy Test
        uses: percy/exec-action@v0.3.1
        with:
          command: "ember test"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
```


It would be now:


```yml
name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: yarn
      - name: Percy Test
        run: npx percy exec -- ember test
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
```
